name: Laporan Bug
description: Membuat laporan bug atau error
title: "Bug/error: "
labels: ['bug']

body:
  - type: markdown
    attributes:
      value: |
        Terima kasih sudah meluangkan waktu untuk membuat laporan bug/error.

        Sebelum Anda memulai, pastikan tidak ada issue yang sama. Silakan mencari terlebih dahulu di issue yang sudah di [close](https://github.com/OpenSID/OpenSID/issues?q=is%3Aissue+is%3Aclosed) atau di [rilis yang akan datang](https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang).
        
        **Jika bug yang dimaksud sudah diperbaiki pada rilis yang akan datang silakan menunggu perbaikan tersebut dirilis. Laporan Bug hanya akan dikerjakan kalau error yang dilaporkan masih terjadi di versi Premium terbaru. Untuk memastikan itu, periksa error tersebut masih terjadi di https://berputar.opendesa.id.**

        Harap tidak melaporkan masalah instal OpenSID atau pertanyaan penggunaan OpenSID. Masalah pada waktu install atau pertanyaan penggunaan OpenSID harap ditanyakan di https://www.facebook.com/groups/komunitasopendesa 
        atau di https://t.me/komunitasopensidstop, karena terkait sistem masing2 pengguna.

        ---
        
  - type: textarea
    id: error_dialami
    attributes:
      label: Jelaskan error yg dialami
      description: |
        Berikan keterangan yg jelas dan singkat mengenai error yg dialami. 
        Pastikan error ini juga ditemukan di https://berputar.opendesa.id.
    validations:
      required: true

  - type: textarea
    id: error_sumber
    attributes:
      label: Cara untuk mereplikasi errornya
      description: |
        Langkah untuk mereplikasi error yg dialami, misalnya:
        1. Pergi ke halaman '...'
        2. Klik tombol '....'
        3. Gulir ke bawah sampai '....'
        4. Lihat error
    validations:
      required: true

  - type: textarea
    id: result
    attributes:
      label: Hasil yg diharapkan
      description: Berikan keterangan yg jelas dan singkat apa hasil yg diharapkan.
    validations:
      required: true

  - type: textarea
    id: error_log
    attributes:
      label: Tangkapan layar dan log error
      description: |
        Lampirkan tangkapan layar yang menjelaskan permasalahan.
        Lampirkan isi file di folder `logs` atau tangkapan error di console inspector browser.
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Dampak bug pada layanan
      description: |
        Seberapa dampak bug ini pada layanan? 
        - Kritis, sistem tidak dapat berjalan sama sekali
        - Utama, fungsi utama terganggu
        - Sedang, gangguan kecil, fungsi utama tetap jalan
        - Ringan, masalah tampilan atau kosmetik
      options:
        - Kritis  
        - Utama
        - Sedang
        - Ringan
    validations:
      required: true
    
  - type: dropdown
    id: rilis-version
    attributes:
      label: Rilis Versi OpenSID
      description: |
        Error ini terjadi di OpenSID Umum atau Premium? 
      options:
        - Rilis Premium
        - Rilis Umum
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versi OpenSID
      description: |
        Error ini terjadi di rilis/versi berapa? 
        Rilis Umum (mis. v2306.0.0) atau Premium (mis. v2306.0.0-premium)?
    validations:
      required: true

  - type: input
    id: tema
    attributes:
      label: Tema Yang Digunakan
      description: Sebutkan tema dan versinya yg digunakan
    validations:
      required: false

  - type: textarea
    attributes:
      label: Informasi tambahan
      description: Penjelasan lain yg dapat membantu. Jika error ini hanya terjadi pada data desa anda, berikan akun Telegram anda supaya dapat dihubungi.
    validations:
      required: false
