name: Permintaan Fitur Baru
description: Mengusulkan fitur baru
title: "Permintaan fitur: "
labels: ['Fitur']

body:
  - type: markdown
    attributes:
      value: |
        Terima kasih sudah meluangkan waktu untuk membuat permintaan fitur.

        Sebelum Anda memulai, pastikan tidak ada issue yang sama. Silakan mencari terlebih dahulu di issue yang sudah di [close](https://github.com/OpenSID/OpenSID/issues?q=is%3Aissue+is%3Aclosed) atau di [rilis umum yang akan datang](https://github.com/OpenSID/OpenSID/wiki/Rilis-Umum-Yang-Akan-Datang).
        Permintaan fitur kita batasi untuk pengguna Premium, tetapi jika ada pengguna Umum ingin mengajukan permintaan fitur tetapi digunakan secara global/umum akan dipertimbangkan untuk dianalisis dan diterapkan di versi premium berikutnya.

        
  - type: textarea
    id: kekurangan
    attributes:
      label: Apa kekurangan yg ingin diatasi?
      description: Beri keterangan singkat dan jelas mengapa fitur ini diperlukan.
    validations:
      required: true

  - type: textarea
    id: solusi
    attributes:
      label: Jelaskan solusi yg diinginkan
      description: |
        Beri keterangan singkat dan jelas mengenai fitur yg diinginkan.
        Beri acuan peraturan yg mendasari fitur ini, kalau ada.
        Lampirkan contoh laporan dan tangkapan layar yang diinginkan.
    validations:
      required: true

  - type: textarea
    id: alternatif
    attributes:
      label: Apakah ada alternatif lain
      description: Beri keterangan singkat dan jelas solusi lain yg telah anda pertimbangkan untuk kebutuhan ini.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Untuk versi OpenSID mana
      description: Fitur ini diusulkan untuk versi Rilis Umum (mis. v2306.0.0) atau Rilis Premium (mis. v2306.0.0-premium) yg mana?
    validations:
      required: true

  - type: textarea
    id: tambahan
    attributes:
      label: Informasi tambahan
      description: Beri informasi lainnya yg dapat membantu menjelaskan permintaan ini.
    validations:
      required: false
